<?php

use Phinx\Migration\AbstractMigration;

class ChannelFieldsTableSeeder extends AbstractMigration
{

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $query = $this->adapter->getConnection()->prepare('INSERT INTO channel_fields (`field_id`, `site_id`, `group_id`, `field_name`, `field_label`, `field_instructions`, `field_type`, `field_list_items`, `field_pre_populate`, `field_pre_channel_id`, `field_pre_field_id`, `field_ta_rows`, `field_maxl`, `field_required`, `field_text_direction`, `field_search`, `field_is_hidden`, `field_fmt`, `field_show_fmt`, `field_order`, `field_content_type`, `field_settings`) VALUES (:field_id, :site_id, :group_id, :field_name, :field_label, :field_instructions, :field_type, :field_list_items, :field_pre_populate, :field_pre_channel_id, :field_pre_field_id, :field_ta_rows, :field_maxl, :field_required, :field_text_direction, :field_search, :field_is_hidden, :field_fmt, :field_show_fmt, :field_order, :field_content_type, :field_settings)');

        $query->execute([
            'field_id' => '1',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'assets',
            'field_label' => 'Assets',
            'field_instructions' => '',
            'field_type' => 'assets',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '1',
            'field_content_type' => 'any',
            'field_settings' => 'YToxMjp7czo4OiJmaWxlZGlycyI7czozOiJhbGwiO3M6NDoidmlldyI7czo2OiJ0aHVtYnMiO3M6MTA6InRodW1iX3NpemUiO3M6NToic21hbGwiO3M6MTQ6InNob3dfZmlsZW5hbWVzIjtzOjE6Im4iO3M6OToic2hvd19jb2xzIjthOjE6e2k6MDtzOjQ6Im5hbWUiO31zOjU6Im11bHRpIjtzOjE6InkiO3M6MTg6ImZpZWxkX3Nob3dfc21pbGV5cyI7czoxOiJuIjtzOjE5OiJmaWVsZF9zaG93X2dsb3NzYXJ5IjtzOjE6Im4iO3M6MjE6ImZpZWxkX3Nob3dfc3BlbGxjaGVjayI7czoxOiJuIjtzOjI2OiJmaWVsZF9zaG93X2Zvcm1hdHRpbmdfYnRucyI7czoxOiJuIjtzOjI0OiJmaWVsZF9zaG93X2ZpbGVfc2VsZWN0b3IiO3M6MToibiI7czoyMDoiZmllbGRfc2hvd193cml0ZW1vZGUiO3M6MToibiI7fQ==',
        ]);

        $query->execute([
            'field_id' => '2',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'checkboxes',
            'field_label' => 'Checkboxes',
            'field_instructions' => '',
            'field_type' => 'checkboxes',
            'field_list_items' => 'A
B
C',
            'field_pre_populate' => 'n',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '2',
            'field_content_type' => 'any',
            'field_settings' => 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30=',
        ]);

        $query->execute([
            'field_id' => '3',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'date_field',
            'field_label' => 'Date',
            'field_instructions' => '',
            'field_type' => 'date',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '3',
            'field_content_type' => 'any',
            'field_settings' => 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30=',
        ]);

        $query->execute([
            'field_id' => '4',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'fieldpack_checkboxes',
            'field_label' => 'Fieldpack Checkboxes',
            'field_instructions' => '',
            'field_type' => 'fieldpack_checkboxes',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'xhtml',
            'field_show_fmt' => 'n',
            'field_order' => '4',
            'field_content_type' => 'any',
            'field_settings' => 'YTo3OntzOjc6Im9wdGlvbnMiO2E6Mzp7czoxOiJBIjtzOjE6IkEiO3M6MToiQiI7czoxOiJCIjtzOjE6IkMiO3M6MToiQyI7fXM6MTg6ImZpZWxkX3Nob3dfc21pbGV5cyI7czoxOiJuIjtzOjE5OiJmaWVsZF9zaG93X2dsb3NzYXJ5IjtzOjE6Im4iO3M6MjE6ImZpZWxkX3Nob3dfc3BlbGxjaGVjayI7czoxOiJuIjtzOjI2OiJmaWVsZF9zaG93X2Zvcm1hdHRpbmdfYnRucyI7czoxOiJuIjtzOjI0OiJmaWVsZF9zaG93X2ZpbGVfc2VsZWN0b3IiO3M6MToibiI7czoyMDoiZmllbGRfc2hvd193cml0ZW1vZGUiO3M6MToibiI7fQ==',
        ]);

        $query->execute([
            'field_id' => '5',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'fieldpack_dropdown',
            'field_label' => 'Fieldpack Dropdown',
            'field_instructions' => '',
            'field_type' => 'fieldpack_dropdown',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'xhtml',
            'field_show_fmt' => 'n',
            'field_order' => '5',
            'field_content_type' => 'any',
            'field_settings' => 'YTo3OntzOjc6Im9wdGlvbnMiO2E6Mzp7czoxOiJBIjtzOjE6IkEiO3M6MToiQiI7czoxOiJCIjtzOjE6IkMiO3M6MToiQyI7fXM6MTg6ImZpZWxkX3Nob3dfc21pbGV5cyI7czoxOiJuIjtzOjE5OiJmaWVsZF9zaG93X2dsb3NzYXJ5IjtzOjE6Im4iO3M6MjE6ImZpZWxkX3Nob3dfc3BlbGxjaGVjayI7czoxOiJuIjtzOjI2OiJmaWVsZF9zaG93X2Zvcm1hdHRpbmdfYnRucyI7czoxOiJuIjtzOjI0OiJmaWVsZF9zaG93X2ZpbGVfc2VsZWN0b3IiO3M6MToibiI7czoyMDoiZmllbGRfc2hvd193cml0ZW1vZGUiO3M6MToibiI7fQ==',
        ]);

        $query->execute([
            'field_id' => '6',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'fieldpack_list',
            'field_label' => 'Fieldpack List',
            'field_instructions' => '',
            'field_type' => 'fieldpack_list',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'xhtml',
            'field_show_fmt' => 'n',
            'field_order' => '6',
            'field_content_type' => 'any',
            'field_settings' => 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30=',
        ]);

        $query->execute([
            'field_id' => '7',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'fieldpack_multiselect',
            'field_label' => 'Fieldpack Multiselect',
            'field_instructions' => '',
            'field_type' => 'fieldpack_multiselect',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'xhtml',
            'field_show_fmt' => 'n',
            'field_order' => '7',
            'field_content_type' => 'any',
            'field_settings' => 'YTo3OntzOjc6Im9wdGlvbnMiO2E6Mzp7czoxOiJBIjtzOjE6IkEiO3M6MToiQiI7czoxOiJCIjtzOjE6IkMiO3M6MToiQyI7fXM6MTg6ImZpZWxkX3Nob3dfc21pbGV5cyI7czoxOiJuIjtzOjE5OiJmaWVsZF9zaG93X2dsb3NzYXJ5IjtzOjE6Im4iO3M6MjE6ImZpZWxkX3Nob3dfc3BlbGxjaGVjayI7czoxOiJuIjtzOjI2OiJmaWVsZF9zaG93X2Zvcm1hdHRpbmdfYnRucyI7czoxOiJuIjtzOjI0OiJmaWVsZF9zaG93X2ZpbGVfc2VsZWN0b3IiO3M6MToibiI7czoyMDoiZmllbGRfc2hvd193cml0ZW1vZGUiO3M6MToibiI7fQ==',
        ]);

        $query->execute([
            'field_id' => '8',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'fieldpack_pill',
            'field_label' => 'Fieldpack_pill',
            'field_instructions' => '',
            'field_type' => 'fieldpack_pill',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'xhtml',
            'field_show_fmt' => 'n',
            'field_order' => '8',
            'field_content_type' => 'any',
            'field_settings' => 'YTo3OntzOjc6Im9wdGlvbnMiO2E6Mzp7czoxOiJBIjtzOjE6IkEiO3M6MToiQiI7czoxOiJCIjtzOjE6IkMiO3M6MToiQyI7fXM6MTg6ImZpZWxkX3Nob3dfc21pbGV5cyI7czoxOiJuIjtzOjE5OiJmaWVsZF9zaG93X2dsb3NzYXJ5IjtzOjE6Im4iO3M6MjE6ImZpZWxkX3Nob3dfc3BlbGxjaGVjayI7czoxOiJuIjtzOjI2OiJmaWVsZF9zaG93X2Zvcm1hdHRpbmdfYnRucyI7czoxOiJuIjtzOjI0OiJmaWVsZF9zaG93X2ZpbGVfc2VsZWN0b3IiO3M6MToibiI7czoyMDoiZmllbGRfc2hvd193cml0ZW1vZGUiO3M6MToibiI7fQ==',
        ]);

        $query->execute([
            'field_id' => '9',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'fieldpack_radio',
            'field_label' => 'Fieldpack Radio',
            'field_instructions' => '',
            'field_type' => 'fieldpack_radio_buttons',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'xhtml',
            'field_show_fmt' => 'n',
            'field_order' => '9',
            'field_content_type' => 'any',
            'field_settings' => 'YTo3OntzOjc6Im9wdGlvbnMiO2E6Mzp7czoxOiJBIjtzOjE6IkEiO3M6MToiQiI7czoxOiJCIjtzOjE6IkMiO3M6MToiQyI7fXM6MTg6ImZpZWxkX3Nob3dfc21pbGV5cyI7czoxOiJuIjtzOjE5OiJmaWVsZF9zaG93X2dsb3NzYXJ5IjtzOjE6Im4iO3M6MjE6ImZpZWxkX3Nob3dfc3BlbGxjaGVjayI7czoxOiJuIjtzOjI2OiJmaWVsZF9zaG93X2Zvcm1hdHRpbmdfYnRucyI7czoxOiJuIjtzOjI0OiJmaWVsZF9zaG93X2ZpbGVfc2VsZWN0b3IiO3M6MToibiI7czoyMDoiZmllbGRfc2hvd193cml0ZW1vZGUiO3M6MToibiI7fQ==',
        ]);

        $query->execute([
            'field_id' => '10',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'fieldpack_switch',
            'field_label' => 'Fieldpack Switch',
            'field_instructions' => '',
            'field_type' => 'fieldpack_switch',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '10',
            'field_content_type' => 'any',
            'field_settings' => 'YToxMTp7czo5OiJvZmZfbGFiZWwiO3M6MjoiTk8iO3M6Nzoib2ZmX3ZhbCI7czowOiIiO3M6ODoib25fbGFiZWwiO3M6MzoiWUVTIjtzOjY6Im9uX3ZhbCI7czoxOiJ5IjtzOjc6ImRlZmF1bHQiO3M6Mzoib2ZmIjtzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30=',
        ]);

        $query->execute([
            'field_id' => '11',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'file',
            'field_label' => 'File',
            'field_instructions' => '',
            'field_type' => 'file',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '11',
            'field_content_type' => 'any',
            'field_settings' => 'YToxMDp7czoxODoiZmllbGRfY29udGVudF90eXBlIjtzOjM6ImFsbCI7czoxOToiYWxsb3dlZF9kaXJlY3RvcmllcyI7czozOiJhbGwiO3M6MTM6InNob3dfZXhpc3RpbmciO3M6MToibiI7czoxMjoibnVtX2V4aXN0aW5nIjtiOjA7czoxODoiZmllbGRfc2hvd19zbWlsZXlzIjtzOjE6Im4iO3M6MTk6ImZpZWxkX3Nob3dfZ2xvc3NhcnkiO3M6MToibiI7czoyMToiZmllbGRfc2hvd19zcGVsbGNoZWNrIjtzOjE6Im4iO3M6MjY6ImZpZWxkX3Nob3dfZm9ybWF0dGluZ19idG5zIjtzOjE6Im4iO3M6MjQ6ImZpZWxkX3Nob3dfZmlsZV9zZWxlY3RvciI7czoxOiJuIjtzOjIwOiJmaWVsZF9zaG93X3dyaXRlbW9kZSI7czoxOiJuIjt9',
        ]);

        $query->execute([
            'field_id' => '12',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'grid',
            'field_label' => 'Grid',
            'field_instructions' => '',
            'field_type' => 'grid',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'xhtml',
            'field_show_fmt' => 'n',
            'field_order' => '12',
            'field_content_type' => 'any',
            'field_settings' => 'YTo4OntzOjEzOiJncmlkX21pbl9yb3dzIjtpOjA7czoxMzoiZ3JpZF9tYXhfcm93cyI7czowOiIiO3M6MTg6ImZpZWxkX3Nob3dfc21pbGV5cyI7czoxOiJuIjtzOjE5OiJmaWVsZF9zaG93X2dsb3NzYXJ5IjtzOjE6Im4iO3M6MjE6ImZpZWxkX3Nob3dfc3BlbGxjaGVjayI7czoxOiJuIjtzOjI2OiJmaWVsZF9zaG93X2Zvcm1hdHRpbmdfYnRucyI7czoxOiJuIjtzOjI0OiJmaWVsZF9zaG93X2ZpbGVfc2VsZWN0b3IiO3M6MToibiI7czoyMDoiZmllbGRfc2hvd193cml0ZW1vZGUiO3M6MToibiI7fQ==',
        ]);

        $query->execute([
            'field_id' => '13',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'matrix',
            'field_label' => 'Matrix',
            'field_instructions' => '',
            'field_type' => 'matrix',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '13',
            'field_content_type' => 'any',
            'field_settings' => 'YTozOntzOjg6Im1pbl9yb3dzIjtzOjE6IjAiO3M6ODoibWF4X3Jvd3MiO3M6MDoiIjtzOjc6ImNvbF9pZHMiO2E6Mzp7aTowO2k6MTtpOjE7aToyO2k6MjtpOjM7fX0=',
        ]);

        $query->execute([
            'field_id' => '14',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'multiselect',
            'field_label' => 'Multiselect',
            'field_instructions' => '',
            'field_type' => 'multi_select',
            'field_list_items' => 'A
B
C',
            'field_pre_populate' => 'n',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '14',
            'field_content_type' => 'any',
            'field_settings' => 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30=',
        ]);

        $query->execute([
            'field_id' => '15',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'playa',
            'field_label' => 'Playa',
            'field_instructions' => '',
            'field_type' => 'playa',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '15',
            'field_content_type' => 'any',
            'field_settings' => 'YToxMzp7czo1OiJtdWx0aSI7czoxOiJ5IjtzOjc6ImV4cGlyZWQiO3M6MToibiI7czo2OiJmdXR1cmUiO3M6MToieSI7czo4OiJlZGl0YWJsZSI7czoxOiJuIjtzOjg6ImNoYW5uZWxzIjthOjE6e2k6MDtzOjE6IjIiO31zOjc6Im9yZGVyYnkiO3M6NToidGl0bGUiO3M6NDoic29ydCI7czozOiJBU0MiO3M6MTg6ImZpZWxkX3Nob3dfc21pbGV5cyI7czoxOiJuIjtzOjE5OiJmaWVsZF9zaG93X2dsb3NzYXJ5IjtzOjE6Im4iO3M6MjE6ImZpZWxkX3Nob3dfc3BlbGxjaGVjayI7czoxOiJuIjtzOjI2OiJmaWVsZF9zaG93X2Zvcm1hdHRpbmdfYnRucyI7czoxOiJuIjtzOjI0OiJmaWVsZF9zaG93X2ZpbGVfc2VsZWN0b3IiO3M6MToibiI7czoyMDoiZmllbGRfc2hvd193cml0ZW1vZGUiO3M6MToibiI7fQ==',
        ]);

        $query->execute([
            'field_id' => '16',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'radio',
            'field_label' => 'Radio',
            'field_instructions' => '',
            'field_type' => 'radio',
            'field_list_items' => 'A
B
C',
            'field_pre_populate' => 'n',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '16',
            'field_content_type' => 'any',
            'field_settings' => 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30=',
        ]);

        $query->execute([
            'field_id' => '17',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'relationships',
            'field_label' => 'Relationships',
            'field_instructions' => '',
            'field_type' => 'relationship',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'xhtml',
            'field_show_fmt' => 'n',
            'field_order' => '17',
            'field_content_type' => 'any',
            'field_settings' => 'YToxNjp7czo4OiJjaGFubmVscyI7YToxOntpOjA7czoxOiIyIjt9czo3OiJleHBpcmVkIjtpOjA7czo2OiJmdXR1cmUiO2k6MDtzOjEwOiJjYXRlZ29yaWVzIjthOjA6e31zOjc6ImF1dGhvcnMiO2E6MDp7fXM6ODoic3RhdHVzZXMiO2E6MDp7fXM6NToibGltaXQiO3M6MzoiMTAwIjtzOjExOiJvcmRlcl9maWVsZCI7czo1OiJ0aXRsZSI7czo5OiJvcmRlcl9kaXIiO3M6MzoiYXNjIjtzOjE0OiJhbGxvd19tdWx0aXBsZSI7czoxOiIxIjtzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30=',
        ]);

        $query->execute([
            'field_id' => '18',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'select',
            'field_label' => 'Select',
            'field_instructions' => '',
            'field_type' => 'select',
            'field_list_items' => 'A
B
C',
            'field_pre_populate' => 'n',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '18',
            'field_content_type' => 'any',
            'field_settings' => 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30=',
        ]);

        $query->execute([
            'field_id' => '19',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'text',
            'field_label' => 'Text',
            'field_instructions' => '',
            'field_type' => 'text',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '19',
            'field_content_type' => 'any',
            'field_settings' => 'YTo3OntzOjE4OiJmaWVsZF9jb250ZW50X3R5cGUiO3M6MzoiYWxsIjtzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30=',
        ]);

        $query->execute([
            'field_id' => '20',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'textarea',
            'field_label' => 'Textarea',
            'field_instructions' => '',
            'field_type' => 'textarea',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '20',
            'field_content_type' => 'any',
            'field_settings' => 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30=',
        ]);

        $query->execute([
            'field_id' => '21',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'rte',
            'field_label' => 'RTE',
            'field_instructions' => '',
            'field_type' => 'rte',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '10',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'xhtml',
            'field_show_fmt' => 'n',
            'field_order' => '21',
            'field_content_type' => 'any',
            'field_settings' => 'YTo4OntzOjI0OiJydGVfZmllbGRfdGV4dF9kaXJlY3Rpb24iO3M6MzoibHRyIjtzOjExOiJydGVfdGFfcm93cyI7czoyOiIxMCI7czoxODoiZmllbGRfc2hvd19zbWlsZXlzIjtzOjE6Im4iO3M6MTk6ImZpZWxkX3Nob3dfZ2xvc3NhcnkiO3M6MToibiI7czoyMToiZmllbGRfc2hvd19zcGVsbGNoZWNrIjtzOjE6Im4iO3M6MjY6ImZpZWxkX3Nob3dfZm9ybWF0dGluZ19idG5zIjtzOjE6Im4iO3M6MjQ6ImZpZWxkX3Nob3dfZmlsZV9zZWxlY3RvciI7czoxOiJuIjtzOjIwOiJmaWVsZF9zaG93X3dyaXRlbW9kZSI7czoxOiJuIjt9',
        ]);

        $query->execute([
            'field_id' => '22',
            'site_id' => '1',
            'group_id' => '1',
            'field_name' => 'wygwam',
            'field_label' => 'Wygwam',
            'field_instructions' => '',
            'field_type' => 'wygwam',
            'field_list_items' => '',
            'field_pre_populate' => '0',
            'field_pre_channel_id' => '0',
            'field_pre_field_id' => '0',
            'field_ta_rows' => '6',
            'field_maxl' => '128',
            'field_required' => 'n',
            'field_text_direction' => 'ltr',
            'field_search' => 'n',
            'field_is_hidden' => 'n',
            'field_fmt' => 'none',
            'field_show_fmt' => 'n',
            'field_order' => '22',
            'field_content_type' => 'any',
            'field_settings' => 'YTo4OntzOjY6ImNvbmZpZyI7czoxOiIyIjtzOjU6ImRlZmVyIjtzOjE6Im4iO3M6MTg6ImZpZWxkX3Nob3dfc21pbGV5cyI7czoxOiJuIjtzOjE5OiJmaWVsZF9zaG93X2dsb3NzYXJ5IjtzOjE6Im4iO3M6MjE6ImZpZWxkX3Nob3dfc3BlbGxjaGVjayI7czoxOiJuIjtzOjI2OiJmaWVsZF9zaG93X2Zvcm1hdHRpbmdfYnRucyI7czoxOiJuIjtzOjI0OiJmaWVsZF9zaG93X2ZpbGVfc2VsZWN0b3IiO3M6MToibiI7czoyMDoiZmllbGRfc2hvd193cml0ZW1vZGUiO3M6MToibiI7fQ==',
        ]);


    }

}
